POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lQGhvbWUuY29tIiwiZXhwIjoxNzMxNTM3NzQwLCJ1c2VySWQiOjJ9.ozjcFZL8VqRGyHvMiVDTPNafX3AR2pGrMDVVg31qIl8