POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lQGhvbWUuY29tIiwiZXhwIjoxNzM2MjkyOTc2LCJ1c2VySWQiOjF9.GSJ0uEuKCajnwNkXL_tWkgHCew2eVnUc9Skj7tQvy-o